### ISSUE TITLE
Feature Request: Is timeshifting possible?

### ISSUE THREAD

**Issue by virtualdj** [BtbN/vlc-htsp-plugin#1]
In the recent TVHeadend versions, it is not possible anymore to pause a channel live HTTP stream because TVHeadend closes it. This is bad because you cannot pause a live event if you're not recording it.

Using your plugin is it possible to use the timeshifting features of TVHeadend to pause the stream from VLC by using HTSP protocol?

I'm using VLC v2.0.5 under Windows 7 (and later I will have to figure out how to compile it under Windows).
Thanks.

**Comment by TomBZombie** [comment]
I can't seem to get this to work. Is there any documentation for this?  Pause works, however if I try to rewind/fast-forward does not. 

I've tried using playback > jump forward/backward/skip to position. They make the video pause for a second and then resume where they left off. Is there anything I need to configure to get this working?
