### ISSUE TITLE
Using the VLC HTSP Plugin

### ISSUE THREAD

**Issue by jwolfley** [BtbN/vlc-htsp-plugin#15]
need instuction on how to install the plugin:

https://tvheadend.org/boards/4/topics/8509

running win7 64, and installed 2.2.0 vlc 64bit. where/what do i put the plugin?

i have tried everything, but wen i restart vlc this plugin does not register:

https://ci.btbn.de/job/vlc-htsp-plugin/ ... bel=linux/

**Comment by BtbN** [comment]
I have not yet updated the build server for vlc 2.2.
The instructions should not change though once i do so.

**Comment by BtbN** [comment]
The build server now produces binaries for vlc 2.2
