### ISSUE TITLE
Latest Stable Plugin does not work with VLC versions above 2.15

### ISSUE THREAD

**Issue by RalphUp** [BtbN/vlc-htsp-plugin#16]
Cannot configure/use the Plugin if you use vlc 2.20. downgrading to 2.15 and the plugin is usable again this is using the •Last build (#117) for Win 32 in Windows 7 64 bit using VLC 32 BIT

**Comment by BtbN** [comment]
Builds and works without changes on vlc 2.2.
The build server just still builds for vlc 2.1.
Not an issue with the plugin.
