### ISSUE TITLE
Vlc 2.2 on Mac not found 

### ISSUE THREAD

**Issue by dercharly** [BtbN/vlc-htsp-plugin#17]
Hello,

i have a Problem. I installed on my new MacBook Vlc 2.2 and this build https://ci.btbn.de/job/vlc-htsp-plugin/PLATFORM=osx,label=osx/124/ i put the Plugin under Vlc -> show content - MacOS - plugins

I can't found the Plugin in settings. Where are the Settings ? I go to Settings and push "show all" but i can't found any settings for htsp.

Is there a Problem? On my old Mac Vlc 2.15 worked with the Plugin but i sold this and forget to backup VLC.

**Comment by BtbN** [comment]
I don't own a mac to test, and the vlc SDK got removed from the OSX vlc releases, so it's possible that external plugins are no longer supported there. Is there anything in the log? Try putting it in the propper subdir, which is access plugins.

**Comment by dercharly** [comment]
i think it is in the proper subdir. This subdir (plugins) have only dylib files like libhttp_plugin.dylib, libhttplive_plugin.dylib.

here is the log (maybe it helps)

core debug: VLC media player - 2.2.0 Weatherwax
core debug: Copyright ¬© 1996-2015 the VideoLAN team
core debug: revision 2.2.0-rc2-290-g1f0f561
core debug: configured with ../extras/package/macosx/../../../configure  '--prefix=/Users/fpk/Desktop/vlc-2.2/release/vlc_install_dir' '--enable-macosx' '--enable-merge-ffmpeg' '--enable-growl' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-shout' '--enable-ncurses' '--enable-twolame' '--enable-realrtsp' '--enable-libass' '--enable-macosx-eyetv' '--enable-macosx-qtkit' '--enable-macosx-avfoundation' '--disable-skins2' '--disable-xcb' '--disable-caca' '--disable-sdl' '--disable-samplerate' '--disable-macosx-dialog-provider' '--with-macosx-version-min=10.6' '--build=x86_64-apple-darwin10' 'build_alias=x86_64-apple-darwin10' 'CC=xcrun clang' 'CFLAGS=' 'LDFLAGS=' 'CXX=xcrun clang++' 'OBJC=xcrun clang'
core debug: VLC media player - 2.2.0 Weatherwax
core debug: Copyright ¬© 1996-2015 the VideoLAN team
core debug: revision 2.2.0-rc2-290-g1f0f561
core debug: configured with ../extras/package/macosx/../../../configure  '--prefix=/Users/fpk/Desktop/vlc-2.2/release/vlc_install_dir' '--enable-macosx' '--enable-merge-ffmpeg' '--enable-growl' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-shout' '--enable-ncurses' '--enable-twolame' '--enable-realrtsp' '--enable-libass' '--enable-macosx-eyetv' '--enable-macosx-qtkit' '--enable-macosx-avfoundation' '--disable-skins2' '--disable-xcb' '--disable-caca' '--disable-sdl' '--disable-samplerate' '--disable-macosx-dialog-provider' '--with-macosx-version-min=10.6' '--build=x86_64-apple-darwin10' 'build_alias=x86_64-apple-darwin10' 'CC=xcrun clang' 'CFLAGS=' 'LDFLAGS=' 'CXX=xcrun clang++' 'OBJC=xcrun clang'

**Comment by BtbN** [comment]
Just filter the settings for htsp and it should be the only entry left.

**Comment by dercharly** [comment]
there is no Filter Field on OS X version of vlc

**Comment by BtbN** [comment]
Well, i have no idea then. Make sure to switch to the advanced view, the simple one does not list it at all.

**Comment by dercharly** [comment]
I switched to Advanced view. There is no htsp Plugin Point. Can Young Tell me were I normally found the htsp plugin point in the settings?

**Comment by dercharly** [comment]
Here is comparison on Mac (left side) and Win (in a virtual machine on the right side).
You can see on Mac there is noch HSTP Point. The Plugin is copied in both installation in the Plugin folder (and of course the Mac Version for Mac and the win version for win)

![bildschirmfoto 2015-03-28 um 11 11 02](https://cloud.githubusercontent.com/assets/4697427/6880604/27f8ee7c-d53b-11e4-8c22-bf3163b869a0.png)

**Comment by BtbN** [comment]
It's not that i didn't believe you. I just have no idea what to do about it. I don't have a mac, won't get one, and have no idea how stuff works there. I'm just cross-compiling binaries and hope they work, which they aparently don't do anymore.

**Comment by dercharly** [comment]
okay. One last question i think version 2.1.5 works with you Plugin. Maybe you can make me the Vlc OS X Plugin für VLC version 2.1.5 an give it to me?so i can test this out?

**Comment by mchsk** [comment]
I can confirm this. My VLC 2.2.1 neither shows libhtsp, however I remember it worked before.

**Comment by mchsk** [comment]
With further investigation I went on trying the plugin with older versions, to find working version. I tried 2.0.0 2.0.9 2.1.0 2.1.5 2.2.0 and guess what, neither worked :< But I remember it worked.. like few months ago?... This is strange. Is there any build avilable before jenkins build #112 for osx?
I am using yosemite @ macbook air.

**Comment by gkovacsp** [comment]
I have the same issue, I'm willing to help to reproduce and the probably you can fix the problem.

**Comment by janeczku** [comment]
The plugin is not loaded on OSX because the libvlccore library is linked incorrectly.
```
[0x1002076e0] main libvlc warning: cannot load module `/Applications/VLC.app/Contents/MacOS/./plugins/libhtsp_plugin.dylib' (dlopen(/Applications/VLC.app/Contents/MacOS/./plugins/libhtsp_plugin.dylib, 1): Library not loaded: @loader_path/lib/libvlccore.8.dylib
  Referenced from: /Applications/VLC.app/Contents/MacOS/./plugins/libhtsp_plugin.dylib
  Reason: image not found)
```
   
`@loader_path/lib/libvlccore.8.dylib` resolves to `Applications/VLC.app/Contents/MacOS/plugins/lib`.
But since the VLC libraries are located in `Applications/VLC.app/Contents/MacOS/lib`, this should be changed to `@loader_path/../lib/libvlccore.8.dylib`

To change the reference after compiling the dylib you can do this:
```
install_name_tool -change "@loader_path/lib/libvlccore.8.dylib" "@loader_path/../lib/libvlccore.8.dylib" "libhtsp_plugin.dylib"
```

**Comment by BtbN** [comment]
Fixed
