### ISSUE TITLE
Jenkins not building OSX

### ISSUE THREAD

**Issue by janeczku** [BtbN/vlc-htsp-plugin#22]
It seems the OSX node is down. Would be cool if we could get current builds for OSX again :)

**Comment by BtbN** [comment]
I can't figure out how to build working OSX plugins. VLC devs just told me that external plugins are not supported.
As i don't have any OSX machines myself, you'll have to figure out how to build it.
If you can tell me what is wrong, i might be able to fix the builder.

**Comment by janeczku** [comment]
@BtbN just to understand: There was a code change in the VLC OSX sources that caused this problem? Because it did work until couple of months ago, didn't it? Sadly its true that the VLC devs are not particular helpful folks, to put it mildly.

**Comment by BtbN** [comment]
Since 2.2 VLC on OSX does not recognize the plugin anymore. I have no idea why, works fine everywhere else.

**Comment by janeczku** [comment]
@BtbN see my comment here: https://github.com/BtbN/vlc-htsp-plugin/issues/17#issuecomment-117058704
