### ISSUE TITLE
How install it on linux Ubuntun x64 ?

### ISSUE THREAD

**Issue by ghost** [BtbN/vlc-htsp-plugin#6]
Hello how install this plugin on vlc linux x64 Ubuntnu 13.10 ?

i have try it to add it on the /usr/lib/vlc/plugins/libhtsp_plugin.so

but vlc don't see it --> http://www.enlightenment.org/ss/e-5291dcb9588ab2.09933217.jpg

how please ??

**Comment by dl9sec** [comment]
Had the same problem and found out, that the install path "/usr/lib/vlc/plugins/access/" doesn't fit to my 64-bit Ubuntu 17.10. On my system the correct path is "/usr/lib/x86_64-linux-gnu/vlc/plugins/access/".
So "sudo cp /usr/lib/vlc/plugins/access/libhtsp_plugin.so /usr/lib/x86_64-linux-gnu/vlc/plugins/access/" will solve the issue...
